### ISSUE TITLE
package json tests need to be added as scripts

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-dominos-pizza-api#10]
A good example for what needs to be added to dev dependancies and script keys can be found here https://github.com/senchalabs/connect/blob/master/package.json

add in whatever your testing dependencies are.

**Comment by RIAEvangelist** [comment]
Once this one is done, I'll be excited to run the suite.

**Comment by madelinecameron** [comment]
Yeah, I can definitely start working on this tonight.

**Comment by RIAEvangelist** [comment]
sweet!

**Comment by madelinecameron** [comment]
Just an update, I have 4 out of 11 tests passing (No tests written for actual order placing or order tracking, may have to figure out a way to test those without actually ordering)

I made a few changes to code (Namely the Address object) so I will push everything tomorrow / tomorrow evening.

The changes to the Address object are: 

* I made it where Line1 and Line2 aren't variables in the object. The reason for this is that the Address object is generally attached to a Customer object which is attached to an Order object which gets passed to Dominos. I didn't know if Dominos would place nice or if it would reject it because the object isn't formatted correctly / malformed so I moved it into its own method to be safe.

* I added the ability to initialize Address objects with arrays (Arrays, string and JSON now supported)

**Comment by RIAEvangelist** [comment]
awesome. Can you add the command to run tests in the ReadMe?

**Comment by madelinecameron** [comment]
Yeah definitely. It is just 'mocha' but I'll add it.

**Comment by RIAEvangelist** [comment]
fixed by b7d2cb7
