### ISSUE TITLE
TypeScript Definitions file

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-dominos-pizza-api#109]
I would like to support typescript users, but I need a `types.d` file for the module to do so easily for Jr devs. I would appreciate it if someone would contribute this file to the repository.

Thank you. 🍕 🥳 🎉

**Comment by mattcroat** [comment]
I'm working on creating the ambient type declarations. :wave:

## Type Definitions

- Types have been added for the examples provided in the `README.md`. Since I expect if they're public there, they should be available everywhere (I say this because some private fields, and method's haven't been added for things like `DominosFormat` where the user isn't expected to use it).
- Types have been added for modules: `Address`, `Customer`, `Image`, `Item`, `Menu`, `NearbyStores`, `Order`, `Payment`, `Store`, `Tracking`.
- I've also added types for things other things use: `urls` from `dominos`, `useInternational`, `canada`, `usa` from `dominos/utils/urls.js`, and `Base64File` used by `Image`.
- I wanted everything to be self-documenting — so almost every field, and method include comments from the documentation. The ones that don't say that, so the user is aware it's intentional.
- You don't have to import modules by hand, they're going to be added as you type since TypeScript knows about them

## How Do We Use It?

Types that aren't part of a library, are ambient type declarations. Hence the `d.ts` extension. There's two options when it comes to using them:

- We can include it as part of the project (easier to maintain, but then it's seen as the burden of the maintainer of the project)
- The other method is including the TypeScript type definitions to [DefinitelyTyped](https://definitelytyped.org/) (more stringent process, but decoupling it from the project)

```sh
npm i -D @types/node @types/dominos
```

The Node types are what a TypeScript user would have to install anyhow — and some of them are used in `@types/dominos`.

## Usage With TypeScript

Since the library is using native JavaScript modules — this poses a problem for TypeScript when using things like `nodemon`, and `ts-node`. I propose if we go through with the type definitions, to include this in the readme. The problem stems from when [ts-node fails when ES Modules are in the dependency graph in Node.js](). These are the steps to get it working:

1. In your `package.json` include `"type": "module"`
2. Your `tsconfig.json` should look like this (not all these are required to be the same):
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": false,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "Node"
  }
}
``` 
3. You have to add a `nodemon.json` config (this is what resolves the issue):
```json
{
  "execMap": {
    "ts": "node --loader ts-node/esm"
  }
}
```

## Feedback

I would prefer if someone more experienced using the library could try out the types first (TypeScript knowledge is not required):

1. Get the [type definition file](https://github.com/mattcroat/types-dominos/blob/main/index.d.ts).
2. `npm i dominos && npm i -D @types/node` inside a folder.
3. Place the `index.d.ts` file at the root of the project, so it gets picked up.
4. Create a `index.ts` file (the name is irrelevant, just make sure it has a `.ts` extension).
5. You don't have to run the actual code, just observe the feedback from your editor.
6. Report anything unexpected.
