### ISSUE TITLE
Need to make sure readme documentation and examples are accurate.

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-dominos-pizza-api#16]

**Comment by RIAEvangelist** [comment]
fixed 9a3b0fe273212e1a8ad0e53861c45e069b9fade5

**Comment by RIAEvangelist** [comment]
https://github.com/RIAEvangelist/node-dominos-pizza-api#dominos-store-info

States 3 classes should be available.

I believe the Item class is missing from the table.

**Comment by madelinecameron** [comment]
It is indeed! That is something that was overlooked. 

Something additional I would like to add is an explaination of Domino's somewhat crazy order structure such as how to structure options (For example, a Pepperoni pizza is XXSCREEN {"P": "1/1", "X": "1/1", "C": "1/1" } if I recall correctly)

Having this documented would be very nice because it is something you have to dig into the Dominos site to figure out and should be documented. I do have this partially figured out on PizzaGiver (In that, only cheese, sausage and pepperoni have the options written out) but it could be fully fleshed out by sort of reverse-engineering their site via in the Chrome Inspect / Dev Console.

**Comment by RIAEvangelist** [comment]
Definitely needed. I think I did this once, but not sure what I did with all the data.

**Comment by RIAEvangelist** [comment]
Also, we need to document the various ways you can pass an address.

It accepts strings, numbers, objects and arrays... a bit too fluid to not have good documentation.

**Comment by madelinecameron** [comment]
Yeah, I agree. Address has grown quite a bit and it would be a nifty feature to note how to use.

**Comment by RIAEvangelist** [comment]
Store Menu examples broken. Store now requires an object with id be passed.

should we require this? if so, docs are out of date.

**Comment by madelinecameron** [comment]
This should be fixed with the new README. Let me know your thoughts.

**Comment by RIAEvangelist** [comment]
Looks great! I noticed a few very very minor things that I'll fix in the morning, like extra ")" etc. looks really good. You definately follow the the first three steps well, especially step 3, BE AWESOME!

**Comment by RIAEvangelist** [comment]
pizzapi.Payment needs documentation.

I'll take care of it tonight and do a once over on all the remaining methods

**Comment by RIAEvangelist** [comment]
oh looks like it has been removed
