### ISSUE TITLE
Accounts support

### ISSUE THREAD

**Issue by reanimus** [RIAEvangelist/node-dominos-pizza-api#47]
This one might be more dicey, but any chance of supporting Domino's "Pizza Profiles" (aka online account)?

**Comment by RIAEvangelist** [comment]
We could support allowing people to utilize the accounts on dominos, however since domino's already stores that information there would be no need for us to dually store it.

I guess the path to this would be :

1. We already have the ability to use accounts on the existing API, maybe extend customer to support this
2. look into account creation api
3. support account creation with domino's api

**Comment by reanimus** [comment]
I figured as much. My big thing is that I'd like the ability to get their rewards thing (essentially a free pizza every 6 orders or so). The ability to use stored payment/address info/orders would be sweet too.

**Comment by RIAEvangelist** [comment]
I think this would still allow that right?

**Comment by reanimus** [comment]
Hopefully! I'm not familiar with the implementation details yet, I just saw it didn't have accounts support at the moment.
